name: "build"
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: |
          yarn
      - run: |
          yarn run all
      - uses: actions/upload-artifact@v3
        with:
          name: sample-spreadsheets
          path: |
            *.fods
            *.ods
            *.xlsx
