name: "build"
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: |
          sudo apt-get update && sudo apt-get install -y libreoffice libreoffice-l10n-de
      - run: |
          yarn
      - run: |
          yarn run all
      - uses: actions/upload-artifact@v4
        with:
          name: sample-spreadsheets
          path: |
            *.fods
            *.ods
            *.xlsx
